feat: implement to 10 users feature
open-sauced/api pull request #200
Opened 2023-07-11 20:33 UTC by OgDev-01

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
[PR Description]

This pull request implements the "Top 10 Users" feature. It adds the necessary functionality to display a list of the top 10 users based on certain criteria. This feature will provide valuable insights into user activity and engagement. The implementation is complete and ready for review.

_Generated using [OpenSauced](https://opensauced.ai/)._

## Related Tickets & Documents
closes https://github.com/open-sauced/ops-backend/issues/76

## Mobile & Desktop Screenshots/Recordings

![image](https://github.com/open-sauced/api/assets/62995161/6d0e4da4-e9c3-45d3-ad8d-7f2cf3bd28be)

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

<img src="https://media2.giphy.com/media/KZTH3kitiDeFi7QfzM/giphy.gif"/>

2023-07-11 20:35 UTC, OgDev-01 commented
I'm not sure I got this right 🫠🫠. I'm open to criticism on this one 😄
cc: @brandonroberts

2023-07-11 20:37 UTC, brandonroberts requested changes

2023-07-11 20:37 UTC, brandonroberts commented on src/highlight/highlight.controller.ts
> +// import { DbUser } from "../user/user.entity";
```suggestion
```

2023-07-11 20:37 UTC, brandonroberts commented on src/highlight/highlight.controller.ts
> +  @Get("/top-10-users")
This endpoint should go in the `users` controller as `/users/top`

2023-07-11 20:37 UTC, brandonroberts commented on src/user/user.service.ts
> +  async findTopTenUsers(): Promise<DbTopUser[]> {
```suggestion
  async findTopUsers(limit = 10): Promise<DbTopUser[]> {
```

2023-07-11 20:37 UTC, brandonroberts commented on src/user/user.service.ts
> +      .limit(10);
```suggestion
      .limit(limit);
```

2023-07-11 20:38 UTC, brandonroberts commented
> I'm not sure I got this right 🫠🫠. I'm open to criticism on this one 😄 cc: @brandonroberts

Pretty close 🙂

2023-07-12 13:45 UTC, brandonroberts requested changes

2023-07-12 13:45 UTC, brandonroberts commented on src/user/user.controller.ts
> +  async getTop10Highlights(@Query() limit: number): Promise<DbTopUser[]> {
Let's remove this for now

```suggestion
  async getTop10Highlights(): Promise<DbTopUser[]> {
```

2023-07-12 13:45 UTC, brandonroberts commented on src/user/user.controller.ts
> +    return this.userService.findTopTenUsers(limit);
Use the default

```suggestion
    return this.userService.findTopUsers();
```

2023-07-12 13:45 UTC, brandonroberts commented on src/user/user.service.ts
> +  async findTopTenUsers(limit = 10): Promise<DbTopUser[]> {
```suggestion
  async findTopUsers(limit = 10): Promise<DbTopUser[]> {
```

2023-07-12 13:54 UTC, brandonroberts approved these changes

2023-07-12 13:54 UTC, merged