Feature: New API endpoint for contributor insights
open-sauced/api pull request #223
Opened 2023-07-25 01:26 UTC by jpmcb

## Description

- Gathers new contributors from last 30 days who did not contribute in previous 30 days based on pull request activity. Date range times are still a WIP.
- Creates new `/contributors/insights/` controller

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Related to some discussion in the Insights repo and during team discussions.

## Mobile & Desktop Screenshots/Recordings

N/a

Running the query with the date/time ranges of 0-30 days inclusive and 30-60 exclusive results in rows of contributors on repos who have not contributed in the exclusive range.

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

n/a

## [optional] What gif best describes this PR or how it makes you feel?

2023-07-25 01:33 UTC, jpmcb commented on src/pull-requests/pull-request.service.ts
> +    range: string
Note to self tomorrow: this needs to _probably_ be a `Date` type since the SQL query when attempting to parse this throws an error with `could not determine data type of parameter`

2023-07-26 17:36 UTC, brandonroberts requested changes

2023-07-26 17:36 UTC, brandonroberts commented on src/contributor/contributor-insights.controller.ts
> +    operationId: "newContributors",
nit: This should match the function name, which should be unique throughout all the operations

```suggestion
    operationId: "newPullRequestContributors",
```

2023-07-26 17:36 UTC, brandonroberts commented on src/pull-requests/pull-request.service.ts
> +    const entities = await queryBuilder.getRawMany();
Let's add a type here, as `getRawMany()` returns a type of `any` because its not tied to the entity
```suggestion
    const entities: DbPullRequestContributor[] = await queryBuilder.getRawMany();
```

2023-07-26 18:09 UTC, brandonroberts approved these changes

2023-07-26 18:09 UTC, brandonroberts commented
🍕

2023-07-26 18:26 UTC, OgDev-01 approved these changes
🍕

2023-07-26 19:18 UTC, merged