feat: adds DB migration with new tables for pizza oven service
open-sauced/api pull request #225
Opened 2023-07-26 21:02 UTC by jpmcb

## Description

This adds 3 tables so that the pizza oven service can integrate directly with the open sauced API and it's data model.

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Related to #218 - once we've arrived on consensus for this data model, this will require a followup in the `pizza` repo to update it's model to integrate with the APIs database.

## Mobile & Desktop Screenshots/Recordings

N/a

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [x] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-07-28 00:30 UTC, jpmcb commented
@brandonroberts - let me know if this looks like the right track: I think this data model will work well for us and let us stitch the `commits` and `repos` tables together nicely.

2023-07-28 18:44 UTC, brandonroberts commented
@jpmcb you're on the right track from what I see so far. I'll take a further look also. We don't need to guard against duplicate repos being baked here correct? That will be done at the pizza oven service level?

2023-07-28 18:47 UTC, jpmcb commented
> We don't need to guard against duplicate repos being baked here correct? That will be done at the pizza oven service level?

Correct. This integration is really twofold: a thin wrapper to send POST requests to the configured pizza oven service and a querier to get commits and things out of the database. Those post requests are forwarded on with little validation. The `pizza` oven microservice handles that side of it all and will connect to the database to add new commits / repos.

2023-07-31 14:05 UTC, AlexHladin commented on src/pizza/commit-authors.service.ts
> +    return new PageDto(entities, pageMetaDto);
@jpmcb you can use [Pager service](https://github.com/open-sauced/api/blob/beta/src/common/services/pager.service.ts) to avoid duplication of code for pagination.

2023-07-31 14:05 UTC, AlexHladin commented on src/pizza/commits.service.ts
> +    return new PageDto(entities, pageMetaDto);
@jpmcb the same here

2023-07-31 14:10 UTC, brandonroberts requested changes

2023-07-31 14:10 UTC, brandonroberts commented on migrations/20230726151100_add_pizza_service_tables.sql
> +create table if not exists public.baked_repos
We could consider adding a `repo_id` as a foreign key for the `repos` table. It may provide an easy indicator of which baked repos that have not been indexed yet.

2023-07-31 14:10 UTC, brandonroberts commented on migrations/20230726151100_add_pizza_service_tables.sql
> +  commit_date timestamp with time zone not null default now(),
We usually store timestamp without the timezone, so when its displayed to the user, there local timezone is used.

```suggestion
  commit_date timestamp without time zone not null default now(),
```

2023-07-31 14:10 UTC, brandonroberts commented on src/pizza/commits.service.ts
> +    queryBuilder.where(`baked_repo_id = ${id}`);
TypeORM will sanitize the input if we use parameterized queries.

```suggestion
    queryBuilder.where(`baked_repo_id = :id`, { id });
```

2023-07-31 14:10 UTC, brandonroberts commented on src/pizza/commits.service.ts
> +    queryBuilder.where(`commit_authors_id = ${id}`);
Same with parameterized queries

2023-07-31 14:10 UTC, brandonroberts commented on src/pizza/pizza-oven.service.ts
> +import { DbBakedRepo } from "./entities/baked-repo.entity";
Let's group the third-party imports at the top, followed by our imports last. I think there's a lint rule we can enable to fix this automatically

2023-07-31 14:10 UTC, brandonroberts commented on src/pizza/pizza-oven.service.ts
> +    queryBuilder.where(`id = ${id}`);
```suggestion
    queryBuilder.where(`id = :id`, { id });
```

2023-07-31 14:19 UTC, jpmcb commented on migrations/20230726151100_add_pizza_service_tables.sql
> +  commit_date timestamp with time zone not null default now(),
I had originally considered using the date/time directly from the commits without the timestamp in the database, but that created some really weird behavior in the pizza service when attempting to get the "latest" commits by date. The wrong commit would be returned since commits are timestamped by the individual commit author (which may have originated from within any timezone),

Attempting to drop them into the database _without_ a timestamp results in the unexpected ordering by date. So, my solution in the pizza service was the convert them during indexing to UTC:

https://github.com/open-sauced/pizza/blob/e99d988bbc30d3fc9fa4e4a6cbb0d789a5298d76/pkg/server/server.go#L169

and enter them in the database with the UTC timestamp explicitly.

2023-07-31 14:21 UTC, jpmcb commented on migrations/20230726151100_add_pizza_service_tables.sql
> +create table if not exists public.baked_repos
Sounds good. That'll probably require a change on the `pizza` side as well to query for a `repo` that has the same `clone_url`

2023-07-31 14:32 UTC, brandonroberts commented on migrations/20230726151100_add_pizza_service_tables.sql
> +create table if not exists public.baked_repos
Ok. If you think using the `clone_url` as the check, I think its fine. Its more so we can check if the repo is index, and also join on this table without using the `clone_url`

2023-07-31 22:21 UTC, bdougie reviewed
Storing public commit emails makes me nervous. I don't know if bcrypt is the answer but I'd love to avoid a [Geekedin situation](https://www.troyhunt.com/8-million-github-profiles-were-leaked-from-geekedins-mongodb-heres-how-to-see-yours/).

2023-08-01 14:33 UTC, jpmcb commented on src/pizza/dtos/commit_authors.dto.ts
> +    example: "hello@opensauced.pizza",
Totally: I think that's wise. We'll want to somehow store those emails in a secure manner so that we can get commit data from users who eventually opt-in with their "known aliases".

Is there any precedence for this currently in our API? Or is this somewhat blocked on #11?

2023-08-01 15:44 UTC, brandonroberts commented
With that concern, I'd recommend not exposing any endpoints for commit authors, and make the commit author email hidden by default by adding a `select: false` to the entity field. 

https://github.com/open-sauced/api/pull/225/files#diff-9a7453839155c8f1da849c06933fa0882375314495c99312e0ae7fc8e8915ce5R21

That way its insert-only. We will need to revisit how we use insights based on this data also. 

On the encryption side, we don't have anything existing there, but I'm sure there's a javascript package our there for bcrypt or whatever we choose to allow us to encrypt the email before inserting the record.

2023-08-01 18:09 UTC, brandonroberts requested changes

2023-08-04 15:06 UTC, jpmcb commented
Revisiting this and pushed changes that address:

- Use the `"id = :id", { id }` for sanitizing selecting on id.
- Makes the commit authors field hidden per @brandonroberts's suggestion.
  - Does punting on the encryption bits make sense right now? If this field is hidden via our API, that should at least keep people from scraping emails. But we may want to investigate adding encryption at rest for other services that may read this data from the database.
- Adds a `repo_id` field on the baked repos table that references an id in the repos table.
  - I'm thinking that we'll have the ETL service have a new cron job that attempts to populate this field based on the `clone_url`. I.e., it will attempt to find associated repos and baked repos based on the clone url and set the `repo_id` field for that column.

2023-08-04 15:13 UTC, brandonroberts commented
> Revisiting this and pushed changes that address:
> 
> * Use the `"id = :id", { id }` for sanitizing selecting on id.
> * Makes the commit authors field hidden per @brandonroberts's suggestion.
>   
>   * Does punting on the encryption bits make sense right now? If this field is hidden via our API, that should at least keep people from scraping emails. But we may want to investigate adding encryption at rest for other services that may read this data from the database.
> * Adds a `repo_id` field on the baked repos table that references an id in the repos table.
>   
>   * I'm thinking that we'll have the ETL service have a new cron job that attempts to populate this field based on the `clone_url`. I.e., it will attempt to find associated repos and baked repos based on the clone url and set the `repo_id` field for that column.

Yes, to punting on the encryption. We won't provide any public access to read commit author emails, but more investigation is needed.

I don't think the `repo_id` needs to have a hard reference to the `repos` table. If it does, then we can't insert a baked_repo record for a repo_id that doesn't already exist in our data.

2023-08-05 14:24 UTC, bdougie approved these changes
I happy with the decisions made in this PR and agree we can punt on encryption

2023-08-07 20:20 UTC, jpmcb commented
> I don't think the repo_id needs to have a hard reference to the repos table. If it does, then we can't insert a baked_repo record for a repo_id that doesn't already exist in our data.

So are you thinking this is ok for now? Or should this column be modified somehow to not directly link to a row in the repos table?

2023-08-07 20:31 UTC, brandonroberts commented
> > I don't think the repo_id needs to have a hard reference to the repos table. If it does, then we can't insert a baked_repo record for a repo_id that doesn't already exist in our data.
> 
> So are you thinking this is ok for now? Or should this column be modified somehow to not directly link to a row in the repos table?

It should be modified to not directly link it, as it will fail on insert because of the reference

2023-08-07 22:49 UTC, jpmcb commented
@brandonroberts - made the following change:

```diff
+  -- elastic columns
+
+  -- the repo_id field is used to loosely reference an id from the repos table
+  -- but since git repos may have their commits indexed that have not yet been
+  -- indexed into the repos table, there is not direct correlation.
+  -- Joins can happen across the "clone_url" to find repos that have not yet
+  -- synced to baked_repos.
+  repo_id bigint default null,
+
```

I'm not sure if that's the right approach or if we have precedence for a column that can be null that loosely references the id of another table.

2023-08-08 02:19 UTC, brandonroberts approved these changes
🍕

2023-08-08 13:53 UTC, jpmcb commented
Great! Looks like we have alignment on the data points and decisions made in this PR.

Next steps before this merges:
- get these data changes into the `pizza` oven - https://github.com/open-sauced/pizza/pull/30
- get that version of the `pizza` oven deployed
- merge and release these changes with that deployment of the pizza oven set in the env var

2023-08-14 16:44 UTC, jpmcb commented
Force pushed to rebase on `beta` and address `eslint` issues.

This is ready to merge now 🚢

2023-08-14 16:45 UTC, merged