feat: return all notifications even if they have been read
open-sauced/api pull request #230
Opened 2023-08-01 07:57 UTC by takanome-dev

## Description

This PR refactors the `UserNotificationService` to return all the notifications even if they have been read.

In `UserNotificationController`, the `OmitType` decorator from `@nestjs/swagger` has been added to exclude the `read_at` property from the response type of the `getUserNotifications` endpoint.

_Generated using [OpenSauced](https://opensauced.ai/)._

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #229 
## Mobile & Desktop Screenshots/Recordings

The `read_at` property has been removed from the response example because it's not returned.
| | |
| ------ | ------ |
| ![notif-res-body](https://github.com/open-sauced/api/assets/79809121/ccd9f1d6-bb2e-419f-a315-d9fb53e2e7a1) | ![notif-res-exple](https://github.com/open-sauced/api/assets/79809121/fd75bf18-2b8b-4585-a11d-d82019a78269) |

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-08-01 08:17 UTC, OgDev-01 approved these changes
LGTM

2023-08-01 14:06 UTC, brandonroberts requested changes

2023-08-01 14:06 UTC, brandonroberts commented on src/user/user-notifcation.service.ts
> +      .andWhere("user_notifications.type IN (:...userNotificationTypes)", { userNotificationTypes });
This is going to cause all the notifications to be marked as read for the user every time this endpoint is fetched, which is not what we want. I would recommend filtering the `notificationIds` to only include notifications that have not been read for marking as read also.

2023-08-02 06:18 UTC, takanome-dev commented on src/user/user-notifcation.service.ts
> +      .andWhere("user_notifications.type IN (:...userNotificationTypes)", { userNotificationTypes });
Yeah, I totally missed that, thanks for noticing. In that case, we would want to return the `read_at` property on select queries to properly filter the notifications.

Then, are we going to remove it again before returning the results to the user @brandonroberts?

2023-08-02 13:16 UTC, brandonroberts commented on src/user/user-notifcation.service.ts
> +      .andWhere("user_notifications.type IN (:...userNotificationTypes)", { userNotificationTypes });
Why does it need to be removed?

2023-08-02 13:28 UTC, takanome-dev commented on src/user/user-notifcation.service.ts
> +      .andWhere("user_notifications.type IN (:...userNotificationTypes)", { userNotificationTypes });
Seeing that the API isn't returning it, I thought for some reason we didn't want to return it.

2023-08-02 16:11 UTC, brandonroberts approved these changes

2023-08-02 16:11 UTC, merged