feat: add source user info to the user notifications
open-sauced/api pull request #248
Opened 2023-08-09 15:44 UTC by takanome-dev

## Description
See [comment below](https://github.com/open-sauced/api/pull/248#issuecomment-1673280598)

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #247
## Mobile & Desktop Screenshots/Recordings

![api-notif-relation-resp](https://github.com/open-sauced/api/assets/79809121/c66dd244-927f-47b8-a0fc-bf9f7bce1b7b)

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-08-09 15:46 UTC, takanome-dev commented
Since there are already notifications in the db, we will probably need to update them by setting `from_user` to the username.
```sql
UPDATE public.user_notifications
SET from_user = u.login
FROM public.users u
WHERE public.user_notifications.from_user_id = u.id;
```

2023-08-09 20:42 UTC, brandonroberts commented
@takanome-dev this is not what want we want to do here. We don't need to duplicate the username in the table. The links I posted in the original issue show how to build a reference to the user information from the users table, so it will get the information and attach it to the notification object.

That way it always reflects the user information based on the ID

2023-08-09 22:14 UTC, takanome-dev commented
> The links I posted in the original issue show how to build a reference to the user information from the users table

Oh I didn't get it, thanks for the clarification. So, if I understand better I have to do the following:
- drop the `from_user_id` column in the notifications table
- add `from` column as a foreign key to the `users` table in the notifications table
- add `notifications` column in the `users` table
- join the user with the notifications when retrieving the notifications

Did I get that right, @brandonroberts?

2023-08-09 23:21 UTC, bdougie approved these changes

2023-08-09 23:23 UTC, bdougie requested changes

2023-08-09 23:23 UTC, bdougie commented on src/user/entities/user-notification.entity.ts
> +    length: 32,
I think this will eventually come back to bite us. The limit on GitHub is 39.

https://www.google.com/search?q=what+is+the+limit+for+github+usernames&oq=what+is+the+limit+for+github+usernames&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIHCAEQIRigATIHCAIQIRigATIKCAMQIRgWGB0YHjIKCAQQIRgWGB0YHtIBCDY4NDNqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8

2023-08-10 14:00 UTC, brandonroberts commented
@takanome-dev not quite 😅 

We're not removing any fields from the table. We're using TypeORM's syntax for building SQL joins with code to associate more information with each user notification we query.

With the notifications, we already have the `from_user_id`, so we want to go fetch the `DbUser` from the `users` table and include it with each notification.

Its a multi-step process to setup.

## Set up the One to Many from User -> User Notification

In the `DbUser` entity, we connect one user to many `DbNotification` records by adding a `OneToMany` relationship

```ts
export class DbUser {
  // other entity fields...

  @ApiHideProperty()
  @OneToMany(() => DbUserNotification, (fromUserNotifications) => fromUserNotifications.from_user)
  public from_user_otifications: DbUserNotification[];
}
```

## Set up the Many to One for UserNotifcation -> User

In the `DbUserNotification` entity, we connect many `DbUserNotification` records back to one user by adding a many to one relationship

```ts
export class DbUserNotifcation {
  // other entity fields...

  @ApiHideProperty()
  @ManyToOne(() => DbUser, (user) => user.from_user_otifications)
  @JoinColumn({
    name: "from_user_id",
    referencedColumnName: "id",
  })
  public from_user: DbUser;
}
```

## Add the field to the query builder

Now,  you can query notifications and request that the `from_user` be populated with the `DbUser` based on the `from_user_id`

```ts
    const queryBuilder = this.baseQueryBuilder(); // user_notifications query builder

    queryBuilder
      .innerJoinAndSelect("user_notifications.from_user", "from_user")
```

TypeORM will attach each notification with a `from_user` property in the returned data.

```
{
  // other user notification fields ...

  from_user_id: 42211
  from_user: {
    login: 'brandonroberts'
    // ... more user fields
  }
}
```

Hopefully this clears things up a bit

2023-08-10 19:40 UTC, takanome-dev commented
Wow!! Thanks so much @brandonroberts 

<img src="https://media1.giphy.com/media/vCKC987OpQAco/giphy.gif"/>

2023-08-10 19:43 UTC, takanome-dev commented on src/user/entities/user-notification.entity.ts
> +    length: 32,
should I update that as well @bdougie?

2023-08-11 15:02 UTC, brandonroberts approved these changes

2023-08-11 23:16 UTC, bdougie approved these changes
Thanks for the direction on this one @brandonroberts

2023-08-12 01:15 UTC, merged