add tagged repos to user highlights
open-sauced/api pull request #263
Opened 2023-08-16 16:45 UTC by diivi

## Description

Should (?) add a tagged repos (array) column to the user-highlights table.
Kinda a shot in the dark since I didn't know how to test it.

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-08-16 21:15 UTC, brandonroberts requested changes

2023-08-16 21:15 UTC, brandonroberts commented on src/user/entities/user-highlight.entity.ts
> +  @ApiModelProperty({
This needs to be added to the DTO also for validation on entry

https://github.com/open-sauced/api/blob/beta/src/user/dtos/create-user-highlight.dto.ts

2023-08-16 21:43 UTC, takanome-dev commented
Tested this and a couple things needs to be done
- Add `taggedRepos` in `create-user-highlight-dto`
```js
  @ApiProperty({
    description: "An array of full-names of tagged repositories",
    example: ["open-sauced/insights", "open-sauced/ai"],
    type: [String],
    isArray: true,
  })
  @IsArray()
  @IsString({ each: true })
  public taggedRepos: string[];
```
- Rename `taggedRepos` to `tagged_repos` in user-highlight.entity since that's the name you used in the db migration
- Update `addUserHighlight` method
```diff
 async addUserHighlight(userId: number, highlight: CreateUserHighlightDto) {
    const newUserHighlight = this.userHighlightRepository.create({
      user_id: userId,
      url: highlight.url,
      highlight: highlight.highlight,
      title: highlight.title ?? "",
      shipped_at: highlight.shipped_at ? new Date(highlight.shipped_at) : new Date(),
      type: highlight.type,
+      tagged_repos: highlight.taggedRepos,
    });
/// ...
}
```

![2023-08-16_21-38](https://github.com/open-sauced/api/assets/79809121/fc42f4aa-12ec-4779-a20a-f9482c1d59f8)

2023-08-17 03:33 UTC, diivi commented
Thanks for running this on your instance @takanome-dev, I should probably spin up a personal database now too 😅

2023-08-17 10:37 UTC, takanome-dev approved these changes

2023-08-17 14:05 UTC, brandonroberts approved these changes

2023-08-17 14:06 UTC, merged