feat: show reactors who reacted to highlights
open-sauced/api pull request #268
Opened 2023-08-21 14:42 UTC by diivi

## Description

This PR adds an endpoint that will show who reacted to a highlight and with what reaction.
![image](https://github.com/open-sauced/api/assets/41837037/4e4c824a-bfed-4daa-927e-db6a12e0e77b)

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-08-21 16:32 UTC, bdougie commented on swagger.yaml
> +  - url: https://api.opensauced.pizza
Does this need to be switched back?

2023-08-21 17:24 UTC, diivi commented on swagger.yaml
> +  - url: https://api.opensauced.pizza
Not sure why this got changed 😅, but I'm fine with reverting.

2023-08-22 14:48 UTC, brandonroberts commented on src/user/user-highlights.service.ts
> +  async findAllHighlightReactionsAndReactors(highlightId: number) {
Why can't this replace the query used in `findAllHighlightReactions`?

2023-08-22 15:23 UTC, brandonroberts commented on src/user/user-highlights.service.ts
> +  async findAllHighlightReactionsAndReactors(highlightId: number) {
As long as it produces the same results for the existing requests, it should be just be adding the array of reactors.

2023-08-22 16:33 UTC, brandonroberts requested changes

2023-08-23 14:06 UTC, brandonroberts approved these changes
Works as expected locally. Needs merge conflict resolution

2023-08-23 16:48 UTC, bdougie approved these changes

2023-08-23 19:39 UTC, merged