feat: initial commit for PR reviews support
open-sauced/api pull request #332
Opened 2023-09-26 22:54 UTC by jpmcb

## Description

This is the initial commit for PR reviews. Once we have consensus on the shape of the database table, we can merge this and get the backfill to happen and then actually integrate that data.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Related to https://github.com/open-sauced/api/issues/321

## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-10-06 20:56 UTC, brandonroberts requested changes

2023-10-06 20:56 UTC, brandonroberts commented on src/pull-requests/entities/pull-request-review.entity.ts
> +  @PrimaryGeneratedColumn()
Should this be `PrimaryColumn`, as it's not autogenerated?

2023-10-06 20:56 UTC, brandonroberts commented on src/pull-requests/entities/pull-request-review.entity.ts
> +export class DbPullRequestReview extends BaseEntity {
We add all entities to the `imports` array in the TypeOrm section of the  `app.module.ts` also

2023-10-06 20:56 UTC, brandonroberts commented on src/pull-requests/pull-request.controller.ts
> +    summary: "",
Summary?

2023-10-07 01:00 UTC, bdougie approved these changes
🚀

2023-10-09 14:54 UTC, OgDev-01 approved these changes
🍕

2023-10-09 15:10 UTC, brandonroberts approved these changes

2023-10-09 15:10 UTC, merged