feat: add timzone endpoint
open-sauced/api pull request #340
Opened 2023-10-02 13:06 UTC by OgDev-01

## Description
This PR:
- adds endpoint to fetch timezones from the users table

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-10-02 14:11 UTC, brandonroberts requested changes

2023-10-02 14:11 UTC, brandonroberts commented on package.json
> +    "axios": "^1.5.1",
Why are we bringing in axios?

2023-10-02 14:11 UTC, brandonroberts commented on src/user/user.controller.ts
> +  @Get("/timezones")
We should put this in the user-list.controller, so its `/lists/timezones` instead of `/user/timezones`

2023-10-02 14:11 UTC, brandonroberts commented on src/user/services/user.service.ts
> +  async getAllTimezones(): Promise<DbTimezone[]> {
Let's move this to the user-list.service

2023-10-02 14:26 UTC, OgDev-01 commented on package.json
> +    "axios": "^1.5.1",
I was getting a package not found error... but i think it is resolved now

2023-10-02 15:57 UTC, brandonroberts commented
@OgDev-01 remove the npm-shrinkwrap changes also

2023-10-02 16:14 UTC, jpmcb reviewed
I think code wise this looks great and don't let me block on this - but I'm curious however where we get the "source of truth" for our user's time-zones?

I worry about drift and nasty time bugs: I.e., what's stopping me from entering "Mountain Time" (which is a common way of referring to "Mountain Standard Time") when there's the possibility that what I really am looking for is "Mountain Daylight Time" which is used in the United States for daylights-savings switches in the winter.

Since, within our API, the timezone is just a string:

https://github.com/open-sauced/api/blob/bbb197c1f31697e67a802ef23d87a9df968b9446/src/user/user.entity.ts#L425-L433

and in our database table, it's just a varchar:

https://github.com/open-sauced/api/blob/bbb197c1f31697e67a802ef23d87a9df968b9446/migrations/20220510165555_add_users.sql#L30

getting all timezones is really just getting all free-text fields from the 'users' table. 

This rambling is probably a separate issue and something we need to have consensus on at some point in order to prevent timezone based bugs. Ideally, the API would introspect some source of truth for timezones and service that to the frontend.

2023-10-02 16:46 UTC, jpmcb commented
Digging in abit more on my above comment ^ looks like the frontend uses our `lib/util/timezones` in the user settings:

https://github.com/open-sauced/app/blob/beta/components/organisms/UserSettingsPage/user-settings-page.tsx#L306C1-L310C22

which pulls from a constant time zone set we have:

https://github.com/open-sauced/app/blob/504d7e2499a6b2a9dd5beaa560dd9ca7aa6af4c8/lib/utils/timezones.ts

In the future, i think the API should do something similar (or better yet, have a shared opensauced-sdk that _both_ the API and the frontend can use to have the same source of truth)

2023-10-02 16:46 UTC, jpmcb commented
Jinx @brandonroberts !! Thanks for the info: again, not blocking, just making comment and hoping to avoid time bugs in the future.

2023-10-03 17:03 UTC, jpmcb approved these changes

2023-10-03 17:43 UTC, nickytonline approved these changes
:shipit:

2023-10-03 17:43 UTC, nickytonline commented on src/user-lists/user-list.service.ts
> +      .groupBy("users.timezone");
Refactor (non-blocking): It results in the same thing in this scenario, but would `DISTINCT` not make more sense?

2023-10-04 21:59 UTC, OgDev-01 commented on src/user-lists/user-list.service.ts
> +      .groupBy("users.timezone");
done ✅

2023-10-04 22:18 UTC, nickytonline approved these changes
Thanks Sunday! :shipit:

2023-10-04 23:55 UTC, brandonroberts approved these changes

2023-10-04 23:59 UTC, closed without merging